# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZcaokN507OSPlSr-efTDtIYuw-1v2Wn
"""

import streamlit as st
import numpy as np
import joblib

# Load model dan scaler
model = joblib.load('xgb_model.pkl')
scaler = joblib.load('scaler.pkl')

# Mapping hasil prediksi
status_map_reverse = {0: 'Enrolled', 1: 'Graduate', 2: 'Dropout'}

# Daftar fitur
selected_features = [
    'Curricular_units_2nd_sem_approved',
    'Curricular_units_2nd_sem_grade',
    'Curricular_units_1st_sem_approved',
    'Curricular_units_1st_sem_grade',
    'Admission_grade',
    'Curricular_units_2nd_sem_evaluations',
    'Tuition_fees_up_to_date',
    'Age_at_enrollment',
    'Previous_qualification_grade',
    'Curricular_units_1st_sem_evaluations',
    'Course',
    'Fathers_occupation',
    'Mothers_occupation'
]

st.title("Prediksi Status Mahasiswa")

# Input data
user_input = []
for feat in selected_features:
    if feat in ['Tuition_fees_up_to_date', 'Course', 'Fathers_occupation', 'Mothers_occupation']:
        val = st.number_input(f"{feat} (kategori / kode numerik)", min_value=0)
    else:
        val = st.number_input(f"{feat}", format="%.2f")
    user_input.append(val)

if st.button("Prediksi"):
    # Ubah jadi array dan scaling
    sample = np.array(user_input).reshape(1, -1)
    sample_scaled = scaler.transform(sample)

    # Prediksi
    pred = model.predict(sample_scaled)[0]
    st.write("### Status Mahasiswa:", status_map_reverse[pred])